# https://taskfile.dev

version: '3'

output: 'prefixed'

vars:
  TwtdSvc: twtd
  TwtdExe: twtd{{exeExt}}

tasks:
  default:
    cmds:
      - task -l
    silent: true

  twtd:
    desc: run twtd service
    cmds:
      - task: run-twtd


  build-twtd:
    desc: build twtd service
    deps: [twtd-css, twtd-js, tr-merge]
    cmds:
      - echo "{{.TwtdExe}} building..."
      - go build -v -o {{.TwtdExe}} -ldflags "-w -X {{.Module}}.Version={{.Version}} -X {{.Module}}.Commit={{.Commit}}" cmd/{{.TwtdSvc}}/main.go
      - echo "{{.TwtdExe}} built."
    generates:
      - '{{.TwtdExe}}'
    sources:
      - '**/*.go'
    method: none
    vars:
      Commit:
        sh: git rev-parse --short HEAD
      Version:
        sh: git describe --abbrev=0
      Module:
        sh: go list
    silent: false

  run-twtd:
    cmds:
        - ./twtd --cookie-secret abc --magiclink-secret abc --api-signing-key abc -R --debug --base-url http://localhost:8000 --bind 127.0.0.1:8000 --twts-per-page 5 --name twtxt.cc --feed-sources=http://localhost:8001/we-are-feeds.txt
    deps: [build-twtd]
    desc: run twtd service
    silent: false

  twtd-css:
    cmds:
      - minify -b -o ./internal/static/css/twtxt.min.css ./internal/static/css/[0-9]*-*.css
    sources:
      - internal/css/**/*.css
    generates:
      - internal/static/css/twtxt.min.css

  twtd-js:
    cmds:
      - minify -b -o ./internal/static/js/twtxt.min.js ./internal/static/js/[0-9]*-*.js
    sources:
      - internal/js/**/*.js
    generates:
      - internal/static/js/twtxt.min.js

  tr:
    dir: internal/langs
    cmds:
      - goi18n merge active.*.toml 
    desc: goi18n create

  tr-merge:
    dir: internal/langs
    cmds:
      - goi18n merge active.*.toml translate.*.toml
    desc: goi18n merge

  release:
    desc: release
    deps: [build-twtd]
    cmds:
      # - mkdir -pv ./release/internal/{static,langs}
      - mkdir -pv ./release/internal/static/{css,js}
      - cp -Rpfv ./{{.TwtdExe}} ./release/
      - cp -Rpfv ./internal/static/css/twtxt.min.css ./release/internal/static/css/
      - cp -Rpfv ./internal/static/js/twtxt.min.js ./release/internal/static/js/
      # - cp -Rpfv ./internal/langs/active.*.toml ./release/internal/langs/
      - ./release/{{.TwtdExe}} --cookie-secret abc --magiclink-secret abc --api-signing-key abc -R --base-url http://localhost:8000 --bind 127.0.0.1:8000 --name twtxt.cc

  clean:
    desc: clean
    cmds:
      - rm -rf ./release
