[ErrorGetUser]
hash = "sha1-ae292a347c8c892dff4fc81976b3736fd15cbfc6"
other = "獲取用戶出錯"

[MsgTransferFeedSuccess]
hash = "sha1-562fb7a829c098116e4f3e5eedea209998209fd9"
other = "改變 Feed 所有者成功"

[TransferFeedFormConfirm]
hash = "sha1-1d1a2a5ca176b94b13d6393b44db100201c5cd98"
other = "你確定要將 Feed 轉移到這個用戶？此操作無法撤消！"

[TransferUserFeedSummary]
hash = "sha1-82a625ec39852607779e48c250bbc3b9a1afa838"
other = "改變 <b>{{ .Username }}</b> 所有者"
